steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/${_DOCKER_IMAGE}:${_VERSION}', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${_PROJECT_ID}/${_DOCKER_IMAGE}:${_VERSION}']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set','image','deployment/${_DEPLOYMENT_NAME}','${_DEPLOYMENT_NAME}=gcr.io/${_PROJECT_ID}/${_DOCKER_IMAGE}:${_VERSION}']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
substitutions:
  _VERSION: v1.9
  _PROJECT_ID: compact-circlet-221015
  _DOCKER_IMAGE: app-python-image
  _DEPLOYMENT_NAME: app-python-web
